<a href="https://colab.research.google.com/github/k4404c/MAT-422/blob/main/HW1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.2
**Elements of Linear Algebra**

important topics:


*   Linear Spaces
*   Orthoganality
*   The Gram-Schmidt Process
*   Eigenvalues and Eigenvectors




In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
import math


**Linear Spaces**

*   **linear combination**: $αu_1 + βu_2 = A$
*   **linear subspace**: A linear subspace of V is a subset U ⊆ V that is closed under vector addition and multiplication. $u_1 + u_2 ∈ U, and α*u1 ∈ U$
*   **span**: $span(w_1, . . . , w_m)$ = set of all linear combinations $∑α_i*w_i$








In [2]:
a = np.random.randint(0, 10, [3, 1])
b = np.random.randint(0,10,[3,1])

α = random.randint(1,10)
β = random.randint(1,10)

C = np.concatenate((α*a , β*b), axis = 1)
print(C)


[[ 2 16]
 [16  0]
 [16 20]]


* C is a linear combination of a and b
* a and b span c


* **linear independence**: $∀_i, u_i ∉ span({u_j : j ≠ i}).$ no vectors of a matrix can be written as a linear combination of the other vectors in a matrix. if the determenent of the matrix = 0, the matrix is linearly dependent


In [3]:
def checkIndependence(matrix):
    det = np.linalg.det(matrix)
    print({True: "dependent", False: "independent"} [det == 0])

a = [1,0,0]
b = [0,1,0]
c = [0,0,1]
D = np.stack((a,b,c),axis = 1)
print(D)
checkIndependence(D) #most basic situation, can easily tell independence

a = np.random.randint(0, 10, [3, 1])
b = np.random.randint(0,10,[3,1])
c = np.random.randint(0, 10, [3, 1])
D = np.concatenate((a,b,c),axis = 1)
print(D)
checkIndependence(D)

D = np.concatenate((a,b,2*b),axis = 1)
print(D)
checkIndependence(D)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
independent
[[9 0 5]
 [1 2 5]
 [1 3 8]]
independent
[[9 0 0]
 [1 2 4]
 [1 3 6]]
dependent


* **basis**: a linearly independent spanning set of a matrix V is the basis for V.
* **dimension**: number of vectors within a matrix

**Orthoganality**

 *  (Norm and Inner Product) $⟨u, v⟩ = u · v = ∑u_i*v_i. ||u|| = √(∑ui^2)$
*   orthonoraml: for all i and all j  ≠ i,$⟨u_i, u_j⟩$ = 0, and $||u_i|| = 1$

  if the norm of two vecors is 0, they are orthoganol to eachother.


In [4]:
a = [1,2,3]
b = [4,5,6]


def findNorm(vector):
  sum=0
  for item in vector:
    sum += item**2
  return math.sqrt(sum)

def findInnerProduct(vector1,vector2):
  innerProduct = 0
  for i in range(len(vector1)):
   innerProduct+= vector1[i] * vector2[i]
  return innerProduct

print(findNorm(a))
print(findInnerProduct(a,b))

a = [0,3,4]
b = [3,0,0]

print(findInnerProduct(a,b))


3.7416573867739413
32
0


* **Best Approximate Theorem**: $||v −α u_1||^2 ≥ ||v − v^*||^2$ projection of $v$ onto $u$ is the closest point in $u$ to $v$

In [5]:
u = [1.0,3.0]
v = [3.0,4.0]

vstar = np.multiply((findInnerProduct(v,u)/(findNorm(u))**2),u) #projvu = (<v,u>/||u||^2)*u
print(vstar)

projvONu = (findNorm(v-vstar))**2
print(projvONu)

αu = np.multiply(1.2,u)

projvONαu = (findNorm(v-αu))**2
print(projvONαu)

#projvONu < projvONαu

[1.5 4.5]
2.5000000000000004
3.4000000000000004


**The Gram-Schmidt Process**
5 steps:
  1. Choose $x̅_1$, normalize : $x̂_1 = {x̅_1\over||x_1||}$
  2. Find vector projection of $x_2$ onto $x_1$ : $proj_{x_1} x_2 = <x_2, x̂_1>x̂_1$
  *   $P_1 = <x_2, x̂_1>x̂_1$
  3. $x̂_2 = {{x_2 - P_1}\over{||x_2-P_1||}}$
  * $x̂_1 \perp x̂_2$
  4. Find vector projection of $x_3$ onto $span(x̂_1,x̂_2)$ :
  * $P_2 = <x_3, x̂_1>x̂_1 + P_1 = <x_3, x̂_2>x̂_2$
  5. $x̂_3 = {{x_3 - P_2}\over{||x_3-P_2||}}$
  * $x̂_3 \perp span(x̂_1,x̂_2)$

  * **Repeat steps for larger matrices**












* $q̂_1 = x̂_1$
* $q̂_2 = x̂_2$
* $q̂_3 = x̂_3$

- Q = [$q̂_1, q̂_2, q̂_3$]

* $r_{11} = ||x_1||$
* $r_{12} = <x_2, x̂_1>$
* $r_{13} = <x_3, x̂_1>$
* $r_{22} = ||x_2-p_1||$
* $r_{23} = <x_3, x̂_2>$
* $r_{33} = ||x_3-p_2||$

R = \begin{bmatrix}
    r_{11} & r_{12} & r_{1,3} \\
    0 & r_{22} & r_{23} & \\
    0 & 0 & r_{33}
  \end{bmatrix}
\
A = QR

In [6]:
x1 = [1.0, 0.0, 1.0]
x2 = [0.0, 2.0, 1.0]
x3 = [1.0, 2.0, 1.0]

A = np.concatenate((np.array(x1).reshape(-1,1),np.array(x2).reshape(-1,1),np.array(x3).reshape(-1,1)), axis = 1)
print(A)

x1hat =  (np.multiply(1.0/(findNorm(x1)) , x1))


p1 = np.multiply(findInnerProduct(x2,x1hat),x1hat)

x2hat = np.multiply((1/findNorm(x2-p1)),(x2-p1))

p2 = (np.multiply(findInnerProduct(x3,x1hat),x1hat) + np.multiply(findInnerProduct(x3,x2hat),x2hat))

x3hat = np.multiply(1/findNorm(x3-p2),(x3-p2))

Q = np.stack((x1hat,x2hat,x3hat),axis = 1)
print(Q)

r11 = findNorm(x1)
r12 = findInnerProduct(x2, x1hat)
r22 = findNorm(x2 - p1)
r13 = findInnerProduct(x3,x1hat)
r23 = findInnerProduct(x3,x2hat)
r33 = findNorm(x3 - p2)

R = np.stack(([r11, 0, 0],[r12,r22,0],[r13,r23,r33]),axis = 1)
print(R)

QR = np.dot(Q,R)
print(QR)

print(A-QR) #shows QR is same(basically) as A



[[1. 0. 1.]
 [0. 2. 2.]
 [1. 1. 1.]]
[[ 0.70710678 -0.23570226  0.66666667]
 [ 0.          0.94280904  0.33333333]
 [ 0.70710678  0.23570226 -0.66666667]]
[[1.41421356 0.70710678 1.41421356]
 [0.         2.12132034 1.88561808]
 [0.         0.         0.66666667]]
[[ 1.00000000e+00 -2.74498744e-18  1.00000000e+00]
 [ 0.00000000e+00  2.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00]]
[[0.00000000e+00 2.74498744e-18 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


**Eigenvalues and Eigenvectors**
* Ax = λ x.\
x → eigenvector
λ → eigenvalue\
(λ,x) → eigenpair of $A$\
\
$det(A-λI) = 0$\
$x ∈ nullspace(A-λI)$


* **Diagonalization**\
$A = XΛX^{-1}$\
$A^n = XΛ^nX^{-1}$

$X = [x_1, x_2, ..., x_n]$\
Λ = \begin{bmatrix}
    λ_1 & 0 & 0 & ...\\
    0 & λ_1 & 0 & ...\\
    0 & 0 & λ_1 & ...\\
    ... & ... & ...& λ_n
  \end{bmatrix}
  \
  A matrix A is said to be orthogonally diagonalizable if there are an orthogonal matrix $P$ (with $P^{-1} = P^T )$ and a diagonal matrix $D$ such that
$A = PDP^T = PDP^{−1}$

In [68]:
A = np.stack(([2 , -1], [-1, 2]),axis = -1)
A

def null_space(A, rcond=None):
#source:https://github.com/scipy/scipy/blob/f97ce31736bb3c4a0a0c7db8fde2ee4ebc69e39d/scipy/linalg/decomp_svd.py#L331-L391
    u, s, vh = svd(A, full_matrices=True)
    M, N = u.shape[0], vh.shape[1]
    if rcond is None:
        rcond = numpy.finfo(s.dtype).eps * max(M, N)
    tol = numpy.amax(s) * rcond
    num = numpy.sum(s > tol, dtype=int)
    Q = vh[num:,:].T.conj()
    return Q

eigenvals = np.linalg.eigvals(A)
from scipy.linalg import null_space
eigenvect1 = null_space(A - eigenvals[0]*np.identity(2))
eigenvect2 = null_space(A - eigenvals[1]*np.identity(2))


eigenvectors = np.concatenate((eigenvect1, eigenvect2), axis = 1)
Xinv = np.linalg.inv(eigenvectors)
LAMBDA = np.stack(([eigenvals[0],0],[0,eigenvals[1]]),axis = 1)


XlamXinv = np.dot(eigenvectors , (np.dot(LAMBDA,Xinv)))
A - XlamXinv #basically 0. shows A = X*lam*X^-1





array([[ 0.00000000e+00, -1.11022302e-16],
       [ 2.22044605e-16,  0.00000000e+00]])